version: 2.1

executors:
  tox:
    docker:
      - image: themattrix/tox
    working_directory: ~/repo

commands:
  tox:
    parameters:
      env:
        type: string
    steps:
      - checkout
      - run: tox -e << parameters.env >>

jobs:

  lint:
    executor: tox
    steps:
      - tox: {env: "lint"}

  test-tf19:
    executor: tox
    steps:
      - tox: {env: "test-tf19"}

  test-tf110:
    executor: tox
    steps:
      # Note: We'd prefer to `upload-coverage` alongside the
      # more usual `test` testenv, but because of the isolated
      # test workaround (see `tox.ini`) we're not able to compute
      # coverage for tensorflow versions 1.11.x and 1.12.x.
      # Once we upgrade to >=1.13.x, we can switch back.
      - tox: {env: "test-tf110,upload-coverage"}

  test-tf111:
    executor: tox
    steps:
      - tox: {env: "test-tf111"}

  test-tf112:
    executor: tox
    steps:
      - tox: {env: "test-tf112"}

  test:
    executor: tox
    steps:
      - tox: {env: "test"}

  examples:
    executor: tox
    steps:
      - tox: {env: "examples"}

  mypy:
    executor: tox
    steps:
      - tox: {env: "mypy"}

workflows:
  version: 2
  test:
    jobs:
      - lint
      - test-tf19
      - test-tf110
      - test-tf111
      - test-tf112
      - test
      - examples
      - mypy
